### ISSUE TITLE
Reform throws exception when using I18n error message lookup in custom validation method (but works with lambda)

### ISSUE THREAD

**Issue by tilod** [apotonick/reform#238] opened 2015-07-10 11:45 UTC
Hello,

when I use custom validations in a form and rely on the error message lookup of I18n, an exception is thrown. Minimal example (leaving out any actual validation logic):

```ruby
class UserForm < Reform::Form
  property :email

  # this works
  validate ->{ errors.add :email, :taken }

  # this doesn't  O_o
  validate :uniqueness_of_email
  def uniqueness_of_email
    errors.add :email, :taken
  end
end

UserForm.new(User.new).validate({email: "foo@example.com"})
```

As commented in the example, when I use a lambda for the validation, it works as expected. But when I use a method, it blows up with:

```
NoMethodError: undefined method `lookup_ancestors' for UserForm:Class
```

`#lookup_ancestors` is defined in the `ActiveModel::Translation` module, but including it in the form doesn't help.

I have absolutely no idea what is going wrong. This is a new bug in Reform 2.0. Before the update both ways worked as expected.

**Comment by tilod** [comment] 2015-07-10 13:35
Additional info:

(1) Using a block also works:

```ruby
validate do
  errors.add :email, :taken
end
```

(2) Including `Reform::Form::ActiveModel` doesn't help. It also shouldn't be necessary in my example since it is meant to be in a Rails app. :smirk:

**Comment by apotonick** [comment] 2015-07-11 00:37
I know where the problem is, thanks!

Can you do me a favour and paste an excerpt from your locale file, too, or even better, setup a small test so I can see how that goes wrong?

In Reform 2, we do not include AM::Validations into the form itself anymore to avoid importing a hundred methods. This is why in your case it can't find that `lookup_ancestors` class method. I will try to fix it.

BTW - I will push things towards Lotus::Validations (which are allowed in Reform 2) as the standard validation engine since I want to get rid of Rails and it's madness (which is reflected in this ticket ;) ).

**Comment by tilod** [comment] 2015-07-11 16:46
The default translation file(s) by Sven Fuchs (https://github.com/svenfuchs/rails-i18n/blob/master/rails/locale/en.yml) will do. I will send you a PR in a minute where I put the default english translation file in the dummy app and added three tests to the test suite. The first test uses `validate do ... end` and passes. The second test uses `validate ->{ ... }` and passes too. The third uses `validate :custom_validation_message` and blows up like in my example above. However, with another exeception this time:

```
NoMethodError: undefined method `read_attribute_for_validation' for #<ActiveModelCustomValidationTranslationsTest::SongForm::WithMethod:0x007fee0251fcf0>
```

But my main problem still applies: It works when used with block and lambda, but not with a method.

While Rails is still a great framework, I am also frustrated by the madness you mentioned. But I have to stick with it. Our app is already to complex to port it to Lotus or another framework. I also find Lotus quite promising but not production ready yet. So would it be possible to use the Lotus validations in a Rails app? And speaking of madness: Being a Reform user for two years and an early adopter of Trailblazer, I must say, you gave my fellow programmers and me a rough ride too. :smirk:

**Comment by apotonick** [comment] 2015-07-11 22:32
Yeah, you can use Lotus validations in Rails, Reform is completely decoupled and can delegate validating to other "backends". All I need to implement is the error message generation in Lotus.

I am not planning to complete leave Rails or anything, I love it as a low-level framework with app templates, migrations, test integration, etc. I just want to use as less as possible from it in my layers due to problems described in this issue.

Oh, and please don't confuse "madness" with "innovation"! I know that many things have changed in all my gems in the last couple of months, but that's why Trb is versioned ZERO.3.x (that's a leading zero, right) and Reform got a major bump.

I don't change APIs and structures to annoy people but to provide a better product - a strategy that Rails should adopt instead of keeping its 10-year old design flaws for the sake of Basecamp.

**Comment by apotonick** [comment] 2015-07-12 00:04
@tilod Merci! Please run your code against master, it should be fixed.

**Comment by tilod** [comment] 2015-07-12 01:43
Good to know about the Lotus validations.

Sorry about the "madness thing". It wasn't meant as an offence. I also was not referring to the frequent changes in the APIs. Of course this can be annoying, but as you said, it's innovation and I'm not really complaining about that.

What I meant is, on the one hand Reform and Trailblazer (and Cells too) are really great and make a lot of things much easier and cleaner to implement. A definite :+1: and keep up the good work. On the other hand, it is really hard to "bend" Reform when the problem doesn't fit perfectly in the scheme you describe in the Trailblazer book and the readmes of the gems. Reform is indeed usable "as is" in most cases, but when I have to tweak it, it makes me curse everytime. That's what I meant with "rough ride". One example: In a nested form you cannot access the parent form from a child form. I had a validation in a child form that depended on a property in the parent form. I haven't found an intented way to do this and the ways I came up with myself were super ugly – which I have to admit could be totally my own fault. I can give you more details (about the problem, not my issues :smirk:) if you are interested, maybe in a feature request.

Thanks for the fix. I will try out on monday when I'm at work.

**Comment by apotonick** [comment] 2015-07-12 01:47
I recently ran into something similar (parent form)!!!

Why don't you just ask me instead of cursing? :grimacing: Reform is actually not really as "limited" as it might look, and with the extraction of all the model-related code to Disposable, it is easier to understand. Having a reference to the parent should be simple to implement!

**Comment by tilod** [comment] 2015-07-12 13:00
Ups, I'm so sorry for removing the database.sqlite3! I misinterpreted the git output and thought it came in with my PR, but I actually just changed it.

Referencing the parent form is something I need more often. I would be very happy to see this feature in Reform. Our domain is quite complex and so are our validations.

**Comment by tilod** [comment] 2015-07-13 09:39
I ran master against my code. It works, bug is fixed. Thanks again!

**Comment by apotonick** [comment] 2015-07-13 09:48
2.0.1, only for you! :wink:

**Closed by apotonick** 2015-07-13 09:48 UTC
