### ISSUE TITLE
Question: how to show * in a required field label?

### ISSUE THREAD

**Issue by artemave** [apotonick/reform#185] opened 2015-01-12 21:19 UTC
simple_form does not pick it up (validations are set up differently?)

Thanks!

**Comment by apotonick** [comment] 2015-01-12 22:05
Can you find out how simple_form finds out about this (or maybe we just ask @rafaelfranca)?

**Comment by artemave** [comment] 2015-01-12 22:44
may be this? https://github.com/plataformatec/simple_form/blob/master/lib%2Fsimple_form%2Fhelpers%2Frequired.rb#L20

**Comment by zavan** [comment] 2015-01-19 02:41
Here it displays the * without any different setup, just the presence validation on the field in the form class.

**Comment by apotonick** [comment] 2015-01-19 03:16
I have the same problem, and it is related to the Foundation setup (in [gemgem-trb](https://github.com/apotonick/gemgem-trbrb)). It also does not add classes to errors. If you run the example, you will see it.

It's definitely something with Foundation, are you using that, @artemave ?

**Comment by zavan** [comment] 2015-01-19 03:35
Oh, I'm using Twitter Bootstrap.

**Comment by artemave** [comment] 2015-01-19 10:01
Yes, I am using the Foundation.

**Comment by apotonick** [comment] 2015-01-19 10:05
@artemave Yeah, cool, that proves that something must be wrong with Reform+simple_form+Foundation! I tried but couldn't find out what it was, can you give it a go?

Does it show errors divs for you correctly? For me, it doesn't add the `.errors` class. In general, it seems that it doesn't read the entire foundation/simple_form initializer at all (in gemgem-trb).

**Comment by artemave** [comment] 2015-01-19 10:18
@apotonick I am sorry, I can't help at the moment - in the middle of client work. 

Also, (without giving it too much thought) I don't understand how bootstrap/foundation could possibly affect the lack of `*` since it is just a part of the label text:

```
  # simple_form initializer
  config.label_text = lambda { |label, required, explicit_label|
    "#{required} #{label}"
  }

**Comment by apotonick** [comment] 2015-01-19 10:24
You nailed it, @artemave, this initializer is not considered in my example app! It is probably simple_form that does not "understand" that a Reform object should be treated like a normal model and the initializer has to be applied.

I added random code to the initializer and it did not change anything in Reform's rendering.

**Comment by artemave** [comment] 2015-01-21 11:54
Looks like simple form is not smart enough to figure out `required` in case of conditional/scoped validations. And I was using those. I reckon we should close this issue as it has got nothing to do with reform.

**Comment by apotonick** [comment] 2015-01-21 21:16
@artemave I am pretty sure the problem is the foundation initializer in combo with Reform. @zavan can you verify that your simple_form/bootstrap initializer is run and used with Reform (e.g. by making sure a custom class is added to an input field, or so)?

**Comment by zavan** [comment] 2015-01-21 21:51
It is, my form gets all styled with bootstrap classes, including the "required" ones:

```html
<div class="form-group string required product_code has-error">
  <label class="string required control-label" for="product_code">
  <abbr title="required">*</abbr> Code</label>
  <input class="string required form-control" type="text" value="" name="product[code]" id="product_code">
  <span class="help-block">can't be blank</span>
</div>
```

**Comment by artemave** [comment] 2015-01-21 23:34
simple_form + reform + foundation + requied works for me: https://github.com/artemave/simple-reform

Am I missing something?

**Comment by fran-worley** [comment] 2016-07-07 05:28
Is your errors issue resolved @apotonick ? If so can we close as it looks like this is more of a simple form issue than a reform one. Also if using dry-validation simple form is never going to be able to accurately detect if a field is required so setting it manually is probably the way to go.

**Comment by fran-worley** [comment] 2016-08-09 15:50
I'm going to close this as it's not specific to Foundation (I use Twitter Bootstrap). Essentially SimpleForm isn't smart enough to detect the required setting in all cases. 

Now that we have moved to dry-v SimpleForm really gets it wrong (it seems to set all properties as required) so you're best bet it to declare the `required` option yourself.

**Closed by fran-worley** 2016-08-09 15:50 UTC
Labels: SimpleForm
