### ISSUE TITLE
Can I avoid creating a new class for every item in a collection?

### ISSUE THREAD

**Issue by shepmaster** [apotonick/reform#218] opened 2015-03-30 20:15 UTC
I'd like to have a form with far too many checkboxes (that's product management for you). In my case, I have ~12K items in a collection and each has 7 properties. We hit a pretty slow case. I added some profiler, and saw two hot spots. I also think that theres massive GC churn for recycling all the one-off classes. There's other parts to the form, but that's the big picture.

`Module#module_eval` is called 169908 times, taking ~19 seconds. It is called by `Forwardable#def_instance_delegator` 168319 of those times, of which 168236 are from `Disposable::Composition::ClassMethods#create_accessors`. It gets a bit harder to track from there, as we get to `Hash#each`, which is used all over the place.

Another offender is `Module#name`, which is called 13001 times, taking ~20 seconds. It is called by `Representable#representation_wrap` 12016 of those times, always from ` 	Representable::Hash#to_hash`, which is from `Reform::Contract::Setup#setup_fields`, `Reform::Contract::Setup#initialize`, 12015 times from `Class#new`.

**Comment by apotonick** [comment] 2015-03-31 10:57
Hang on, your form's got 12K fields? Is that really what you want? How do you use the form? I guess you only use the `Contract` functionality without the visual form, right?

Not sure why `Module#name` is called so many times, maybe I'll understand when you tell me how you use your forms. Thanks for the benchmarks, BTW, interesting to see where's the bottlenecks. Reform (so far) was not designed to handle that kind of bulk data, of course! :wink:

**Comment by shepmaster** [comment] 2015-03-31 13:16
> Hang on, your form's got 12K fields?

Yep. Checkboxes and a hidden id field

> Is that really what you want?

Nope, but Product Management overruled us. I can't fix that, I can only work in the constraints I'm given.

> How do you use the form? I guess you only use the Contract functionality without the visual form, right?

I'm not entirely sure what you mean, but we do put actual checkboxes on the HTML page right now. We are going to use JS to add the dreaded [double list box](http://www.msaccesstips.com/uploaded_images/DoubleList-758576.gif) with some sorting / filtering so that our users don't completely hate us, but that is basically checkboxes in a different skin.

> when you tell me how you use your forms.

Again, I'm not entirely following what you mean. The act of calling `MyForm.new(thing1: a, thing2: b)` takes up lots of time, the actual time for rendering isn't that long. I'll see if I can whip up a self-contained example though.

**Comment by shepmaster** [comment] 2015-03-31 13:39
Here's a small standalone script that starts to replicate the behavior. I've left the [ruby-prof](https://github.com/ruby-prof/ruby-prof) stuff hooked in, but be aware that it generates about 400 MB of output.

```ruby
require 'reform'
require 'benchmark'
require 'ruby-prof'

class Form < Reform::Form
  collection :assets do
    property :name1
    property :name2
    property :name3
    property :name4
    property :name5
    property :name6
    property :name7
  end
end

AssetHolder = Struct.new(:assets)
Asset = Struct.new(:name1, :name2, :name3, :name4, :name5, :name6, :name7)
assets = 10000.times.map { |i| Asset.new(i, i, i, i, i, i , i) };
assets_holder = AssetHolder.new(assets);

result = RubyProf.profile do
  Form.new(assets_holder)
end

printer = RubyProf::GraphPrinter.new(result)
printer.print(File.open('graph.txt', 'w'), {})

printer = RubyProf::GraphHtmlPrinter.new(result)
printer.print(File.open('graph.html', 'w'), {})

printer = RubyProf::CallStackPrinter.new(result)
printer.print(File.open('callstack.html', 'w'), {})
```

**Comment by shepmaster** [comment] 2015-03-31 13:41
For my own education, could you help me understand why a new class is generated for every item in the `collection`? It seems as if you could simply create one class for each `property` and each `collection`, and then just instantiate it as appropriate for each item. I honestly don't know if that would improve performance, but I'd *hope* that creating an instance is less expensive than creating a brand-new class.

**Comment by apotonick** [comment] 2015-03-31 16:05
Ok, generally, creating classes is slow, instantiating objects is fast. You're right, we don't need to create an anonymous class per item. But as far as I remember, this only happens once, at compile time and is then reused when going through the items at runtime?!

This is an interesting problem - can you please make sure the bottleneck comes from _creating_ sub form classes per item? I will look into it too. Thanks!!

**Comment by apotonick** [comment] 2015-03-31 16:11
Ah, I got it - the problem is not the class generation for nested forms, but the composition object!

However, looking at how this class is created makes me wonder why this is run for every item: https://github.com/apotonick/reform/blob/master/lib/reform/form/composition.rb#L41

Can you add some debugging [here](https://github.com/apotonick/reform/blob/master/lib/reform/form/composition.rb#L16) and find out whether or not this is cached properly?

**Comment by shepmaster** [comment] 2015-03-31 17:47
I added a `STDERR.puts "called"` at the requested line, but there was no output. I moved it to [this line](https://github.com/apotonick/reform/blob/3b93f66b326ca7ecb79d7a1bf93f69e89d772a28/lib/reform/composition.rb#L18) and saw it get output many times. Not sure what the difference between the two compositions are though.

**Comment by shepmaster** [comment] 2015-03-31 17:48
FWIW, in our real code, we do have a composed form (`FooForm.new(a: ..., b: ...)`), but for reproduction purposes I do not explicitly use form composition.

**Comment by shepmaster** [comment] 2015-03-31 18:09
Maybe [this TODO](https://github.com/apotonick/reform/blob/3b93f66b326ca7ecb79d7a1bf93f69e89d772a28/lib/reform/form.rb#L19-L20) ?

**Comment by apotonick** [comment] 2015-04-02 10:41
Yeah man, you found the problem!

**Comment by shepmaster** [comment] 2015-04-02 11:08
Unfortunately, I don't see how to fix it. That method is called with each instance. I tried a quick hack where I cached the result based on class, but that failed the tests spectacularly. Any suggested paths to investigate?

**Comment by apotonick** [comment] 2015-04-02 11:11
I see a way to fix it. Gimme some hours.

**Comment by shepmaster** [comment] 2015-04-02 19:47
Sounds good. Let me know if I can help or test out something with our true pathological cases!

**Comment by shepmaster** [comment] 2015-04-28 18:32
@apotonick Please let me know what ideas you had so I can implement them and submit a PR.

**Comment by apotonick** [comment] 2015-04-28 21:03
Hey @shepmaster - I am working on Reform 2.0 atm. This will move a lot of code into Disposable and will make this task a lot easier. I'll let you know once we're ready for this!

**Comment by shepmaster** [comment] 2015-05-05 19:41
@apotonick I appreciate that you are working to make the project better for everyone, but we are using the released version of Reform and really want to knock the edge off some of our slowness. I don't want to slow you down on 2.0 work, but I'm totally happy with either doing a local fork or submitting a PR to the 1.x branch. I'd just love to know your idea when you said

> I see a way to fix it. Gimme some hours.

So I could go down that path.

Thanks a million!

**Comment by apotonick** [comment] 2015-05-05 22:23
Hey @shepmaster - I hear ya! Just a quick question: Do you have that problem with `Composition` mixed in, or even without? According to your reports, you're using a composition form, but in your example script, you don't?

**Comment by shepmaster** [comment] 2015-05-06 14:35
@apotonick In the real app, we are mixing in `Composition`, but when I was nailing down a reproducible example, I didn't need `Composition` to trigger the behavior. It's entirely possible that `Composition` is adding to the slowness, but it didn't seem to be required. I'll modify the script a bit to use a composed form, and compare it against the non-composed form.

**Comment by shepmaster** [comment] 2015-05-06 14:43
If I add to the Form:

```ruby
include Reform::Form::Composition
collection :assets, on: :thing1 do
```

and then instantiate it as 

```ruby
Form.new(thing1: assets_holder)
```

```
original: 14.345s
composed: 14.224s
```

The times are close enough that I'd believe them to be measurement noise. So I doubt that the composition is strongly contributing to the times. I think it's likely just that a brand new class is created for every property of every element of the collection.

**Comment by apotonick** [comment] 2015-05-06 22:44
@shepmaster Any chance you could try out this branch: https://github.com/apotonick/reform/tree/jake

I backported an improvement from Reform 2.0 (note that you need representable 1.2.6). This speeds up the setup process around 20%. Still can't find where classes are created unnecessarily, though.

Feel free to book me via codementor or just buy a copy of my book and make 10 other people buy it, too (you asked about paying me for a fix). :rocket: :guitar:

**Comment by apotonick** [comment] 2015-05-07 00:39
So the `jake` branch should help setting up, and then I also found the problem with that new class, it is not related to `Composition`.

**Comment by apotonick** [comment] 2015-05-07 04:44
@shepmaster I added another fix and ran some tests, setup is more than 50% faster now. Please test and report.

In Reform 2.0, we won't have this problem, as we don't need to create underlying anonymous classes in Reform. The datamapping is all cleanly handled in Disposable.

@shepmaster You owe me! Make at least 10 people buy the Trailblazer book! :cake: :stuck_out_tongue_winking_eye:

**Comment by shepmaster** [comment] 2015-05-07 14:51
@apotonick This is great, and things are definitely looking better!

:heart: :yellow_heart: :green_heart: :blue_heart: :purple_heart: 

Here's 1.2.6:

```
Creation:    12.710000   0.090000  12.800000 ( 12.795032)
Validation:   2.670000   0.000000   2.670000 (  2.680905)
Syncing:     15.560000   0.040000  15.600000 ( 15.607207)
```

And the current branch (7fe7dd89642bf9efa353fb9223afb0f914b9e330)

```
Creation:     2.510000   0.050000   2.560000 (  2.583052)
Validation:   2.610000   0.000000   2.610000 (  2.614663)
Syncing:      5.230000   0.010000   5.240000 (  5.234613)
```

[reproduction code](https://gist.github.com/shepmaster/54f0eabbd371f5ad79ed)

As reported via `time(1)`, the total time reduced 32.383 -> 11.668 (**36%** of the previous time).

I also used the branch in our production app. That had 5K items, and times are reported by the Chrome web inspector.

The total time reduced 26.61 -> 16.33 (**61%** of the previous time).

Unfortunately for us, another set of coworkers worked on replacing the `collection` component of the form and overriding `sync` and `validate` with some hand-rolled Ruby. That drops it to 3 seconds! I'll see about better aligning the reproduction with our production example to further investigate.

**Comment by shepmaster** [comment] 2015-05-07 16:07
Here's an [updated script](https://gist.github.com/shepmaster/76e383df03a8e2d63e2d) ripped from our production codebase. I define two forms, `SlowForm` and `FastForm`, and there's a variable to switch between them. As you can see, we just override `sync` and `validate` and do some stuff ourselves. My hope is that we can get Reform to about 1 second :smiling_imp: 

With `Form = SlowForm`:

```
Creation:     7.810000   0.050000   7.860000 (  7.855516)
Validation:   4.380000   0.000000   4.380000 (  4.379169)
Syncing:      9.570000   0.030000   9.600000 (  9.602480)
```

With `Form = FastForm`:

```
Creation:     0.010000   0.000000   0.010000 (  0.001032)
Validation:   0.000000   0.000000   0.000000 (  0.006622)
Syncing:      0.010000   0.000000   0.010000 (  0.011656)
```

**Comment by shepmaster** [comment] 2015-05-07 19:38
Also there's a bit of [debugging](https://github.com/apotonick/reform/commit/5b184686a4231b755ab88a40e643b8141510e1e7#diff-875b9381df398a67180e0521d6ad1f6dR71) [output](https://github.com/apotonick/reform/commit/5b184686a4231b755ab88a40e643b8141510e1e7#diff-875b9381df398a67180e0521d6ad1f6dR154) left over :smile_cat:

**Comment by apotonick** [comment] 2015-05-07 22:07
Good news for you, again. In Reform 2, there's sophisticated change-state support which means entire sub forms know whether or not they've changed after `#validate` and hence can skip validation (if you want that).

I'd love to know _conceptually_ what your team changed in Reform to make it even faster.

**Comment by shepmaster** [comment] 2015-05-08 02:26
> I'd love to know conceptually what your team changed in Reform to make it even faster.

We just removed the `collection` completely from our form. We avoid using Reform at all for that component, overrode `sync` and `validate`, and used straight Ruby methods acting on the input parameters hash. You can [see it](https://gist.github.com/shepmaster/76e383df03a8e2d63e2d#file-second-reproduction-rb-L50-L62) in the example.

**Comment by apotonick** [comment] 2015-05-13 02:56
I am currently working with @mguentner on benchmarks/profiling of Representable and we ran into the same issue you reported, @shepmaster: `Module#name` is a problem!!!

**Comment by apotonick** [comment] 2015-06-17 03:05
This is fixed in Reform 2, which will be released beta in a few days.

**Closed by apotonick** 2015-06-17 03:05 UTC
