### ISSUE TITLE
Checkbox validation with acceptance true

### ISSUE THREAD

**Issue by NicoMartens** [apotonick/reform#394] opened 2016-08-24 11:53 UTC
There seems to be a bug when using 'acceptance: true' as validation for a checkbox as described in Rails Guides http://guides.rubyonrails.org/active_record_validations.html#acceptance. The validation results in a SystemStackError

![systemstackerror](https://cloud.githubusercontent.com/assets/12123584/17929473/117b976a-6a01-11e6-8268-9b7cb7698ef9.png)

The error occurs when the validate method is invoked.

I've provide a minimal example on github https://github.com/NicoMartens/reform-checkbox-validation. It is just a Rails app with a user model and a form_for this user. Start the app an submit the form.

Reform version is reform-rails 0.1.5.

**Comment by apotonick** [comment] 2016-08-24 15:16
Have you seen this? http://trailblazer.to/gems/reform/validation.html#confirm-validation

**Comment by fran-worley** [comment] 2016-09-27 07:58
@NicoMartens this is actually caused by a rails 5 change see trailblazer/reform-rails#30 

I'm closing this here as it's not a reform issue and will need to be resolved in Reform-rails

**Comment by fran-worley** [comment] 2016-09-27 07:59
@apotonick confirm and acceptance unfortunately are not the same thing... One checks that two fields have the same value and the other that a boolean is true.

**Closed by fran-worley** 2016-09-27 07:58 UTC
