### ISSUE TITLE
Nested forms/collections: SystemStackError: stack level too deep and other issues with bi-directionality

### ISSUE THREAD

**Issue by niels** [apotonick/reform#360] opened 2016-04-24 14:35 UTC
In nested objects scenarios – either simple parent <> child or more complex parent <> collection relationships –, reform/disposable can only properly handle one direction. For example, a parent may refer to a child, or a child may refer to a parent, but never can they bi-directionally refer to one another:

```ruby
require "reform"
require "reform/form/dry"

class Reform::Form
  feature Reform::Form::Dry::Validations
end

# Forward declaration to allow for resolving of the circular dependency.
class Parent < Reform::Form; end
class Child < Reform::Form; end

class Parent < Reform::Form
  property :child, form: Child
  property :some_property
end

class Child < Reform::Form
  property :parent, form: Parent
end

# Inverse of relationships isn't set automatically.
parent = Parent.new(OpenStruct.new(child: OpenStruct.new, some_property: nil))
puts parent.child.parent.inspect #=> nil

# When inverse is set manually, the object seems to be duplicated instead of
# referenced as its changes don't propagate.
parent = Parent.new(OpenStruct.new(child: OpenStruct.new, some_property: nil))
parent.child.parent = parent
parent.some_property = "set"
puts parent.child.parent.some_property.inspect #=> nil

# And now for the pièce de résistance…
parent = Parent.new(OpenStruct.new(child: OpenStruct.new, some_property: nil))
parent.deserialize({}) #=> SystemStackError: stack level too deep
```

The first issue of course is perhaps less a bug and more an inconvenience. The second issue I find more serious, though better documentation might suffice to address it (i.e. making it clear that when assigning values to properties, they get duplicated instead of passed along as-is). The third issue seems to be a proper bug?

Backtrace:

```
declarative-0.0.7/lib/declarative/deep_dup.rb:4:in `call'
declarative-0.0.7/lib/declarative/deep_dup.rb:11:in `block in dup_items'
declarative-0.0.7/lib/declarative/deep_dup.rb:11:in `collect'
declarative-0.0.7/lib/declarative/deep_dup.rb:11:in `dup_items'
declarative-0.0.7/lib/declarative/deep_dup.rb:4:in `call'
declarative-0.0.7/lib/declarative/heritage.rb:5:in `record'
declarative-0.0.7/lib/declarative/schema.rb:79:in `register_feature'
representable-3.0.0/lib/representable/hash.rb:13:in `block in included'
representable-3.0.0/lib/representable/hash.rb:10:in `class_eval'
representable-3.0.0/lib/representable/hash.rb:10:in `included'
disposable-0.2.6/lib/disposable/rescheme.rb:34:in `include'
disposable-0.2.6/lib/disposable/rescheme.rb:34:in `block in build_representer'
disposable-0.2.6/lib/disposable/rescheme.rb:33:in `initialize'
disposable-0.2.6/lib/disposable/rescheme.rb:33:in `new'
disposable-0.2.6/lib/disposable/rescheme.rb:33:in `build_representer'
disposable-0.2.6/lib/disposable/rescheme.rb:17:in `from'
disposable-0.2.6/lib/disposable/rescheme.rb:62:in `from_inline!'
disposable-0.2.6/lib/disposable/rescheme.rb:47:in `build_definition!'
disposable-0.2.6/lib/disposable/rescheme.rb:24:in `block in from'
disposable-0.2.6/lib/disposable/twin/definitions.rb:22:in `block in each'
declarative-0.0.7/lib/declarative/definitions.rb:30:in `each'
declarative-0.0.7/lib/declarative/definitions.rb:30:in `each'
disposable-0.2.6/lib/disposable/twin/definitions.rb:16:in `each'
<repeats>
  disposable-0.2.6/lib/disposable/rescheme.rb:21:in `from'
  disposable-0.2.6/lib/disposable/rescheme.rb:62:in `from_inline!'
  disposable-0.2.6/lib/disposable/rescheme.rb:47:in `build_definition!'
  disposable-0.2.6/lib/disposable/rescheme.rb:24:in `block in from'
  disposable-0.2.6/lib/disposable/twin/definitions.rb:22:in `block in each'
  declarative-0.0.7/lib/declarative/definitions.rb:30:in `each'
  declarative-0.0.7/lib/declarative/definitions.rb:30:in `each'
  disposable-0.2.6/lib/disposable/twin/definitions.rb:16:in `each'
</repeats>
disposable-0.2.6/lib/disposable/rescheme.rb:21:in `from'
disposable-0.2.6/lib/disposable/rescheme.rb:12:in `from'
reform-master/lib/reform/form/validate.rb:44:in `deserializer'
reform-master/lib/reform/form/validate.rb:28:in `deserialize'
test.rb:34:in `<top (required)>'
```

Though not exactly the same scenario, this may be related to #261?

**Comment by apotonick** [comment] 2016-04-26 00:00
This is indeed a duplicate of https://github.com/apotonick/reform/issues/261, @niels !

**Closed by apotonick** 2016-04-26 00:00 UTC
